name: build android

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK and AAB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-android-${{ hashFiles('**/package-lock.json') }}

      - name: Install mah build dependencies
        run: npm install

      - name: Install capacitor dependencies
        run: cd resources/mobile && npm install

      - name: Write mah build config
        run: |
          echo "{\"name\": \"Mah\", \"mobile\":true}" > custom-build-config.json

      - name: Build mah with capacitor config
        run: npm run build:capacitor

      - name: Capacitor update
        run: cd resources/mobile && npx cap update

      - name: Capacitor copy
        run: cd resources/mobile && npx cap copy

      - name: Gradle chmod setup
        run: cd resources/mobile/android && chmod +x gradlew

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          echo $ENCODED_STRING | base64 -di > resources/mobile/android/app/mah_keystore.jks

      - name: Build application apks
        run: cd resources/mobile && npm run build:release:apk
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Build application aab
        run: cd resources/mobile && npm run build:release:aab
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload release bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          retention-days: 10
          path: |
            resources/mobile/android/app/build/outputs/apk/release/app-arm64-v8a-release.apk
            resources/mobile/android/app/build/outputs/apk/release/app-armeabi-v7a-release.apk
            resources/mobile/android/app/build/outputs/apk/release/app-x86-release.apk
            resources/mobile/android/app/build/outputs/apk/release/app-x86_64-release.apk
            resources/mobile/android/app/build/outputs/bundle/release/app-release.aab
