name: release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Write github.io app config
        run: |
          echo "{\"name\": \"Mah\", \"kyodai\":true, \"editor\":true}" > custom-build-config.json

      - name: Install dependencies
        run: |
          npm install

      - name: Test
        run: npm run test

      - name: Build GH Pages release
        run: |
          npm run build:deploy-ghpages

      - name: Build GH Pages settings
        run: |
          touch ./dist/.nojekyll

      - name: Deploy to GH Pages branch 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true

      - name: Write release app config
        run: |
          echo "{\"name\": \"Mah\"}" > custom-build-config.json

      - name: Build
        run: |
          npm run build:deploy-release

      - name: Create release package
        run: |
          cd dist && zip -r ./mah-release.zip .

      - name: Generate release log
        run: |
          npm run build:releaselog

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          bodyFile: ./RELEASELOG.md
          draft: false
          prerelease: false
          artifacts: ./dist/mah-release.zip
          artifactContentType: application/zip
          makeLatest: true
