name: test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags-ignore:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-test-${{ hashFiles('**/package-lock.json') }}

      - name: Install mah build dependencies
        run: npm install

      - name: Test
        run: npm run test

      - name: Make a production build
        run: npm run build:prod
